"""Per-question scorecard — the primary deliverable.

The other team controls exactly one lever: **the 48 questions**. The `queries`
inside a web-search call are generated by the model from those questions, so no
report can recommend pruning sub-query #3. That makes per-question rates the only
analysis that maps onto an action someone can actually take, and it is why this
module — not archetype clustering — carries the deletion argument.

Every figure here is a count over stored rows. Nothing is inferred, sampled or
estimated, which is what lets the result survive the "nothing unverifiable goes in
a report" invariant when it lands in front of another team's budget holder.

**The drop-candidate signal is "the answer carried no information"**, which
unifies the two answer regimes rather than needing a rule per question type:

* a text question answering a literal `NULL`, and
* a scale question answering `3` with no evidence — the documented default when
  the search found nothing sufficient.

Both are exactly measurable. A question whose `noinfo` rate is near 100% is
costing search calls to produce a constant.

Question TEXT is never printed. It carries merchant values inline — that is why it
differs per merchant — so a scorecard quoting it could not be pasted back across
the air gap without leaking PII. qnum is the stable key and the only one needed.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass

from .outputs import _norm_text, is_null_answer

# Which stored parse populates the answer under test, most-preferred first.
#
# All three sources are stored side by side at ingest (see db.py's `answers`
# comment), so switching between them is a SQL clause rather than a re-parse of a
# 19k-merchant corpus.
#
# Measured 2026-08-04, and it demotes this flag from load-bearing to marginal:
# `citation_evidence` is co-derived with the prose, not an independent parse of
# it. It covers exactly the runs whose prose parsed and nothing else, and where
# both exist they agree with us on 98.6% of answers. `answer_dict` is the genuinely
# independent one — it differs on 6.0% and is the SOLE source for 50,256 answers.
# So `ce` shifts ~1.4% of answers, and no conclusion should turn on it.
ANSWER_SOURCES: dict[str, str] = {
    "prose": "COALESCE(answer_text, ce_answer)",
    "ce": "COALESCE(ce_answer, answer_text)",
}

# A scale answer is 1-5. Whether it is a bare digit or a digit followed by prose
# is UNCONFIRMED on real data, so both are matched: `'3'` and `'3 - no adverse
# media'` are the same answer. Anchoring on the leading digit and requiring a
# non-digit after it keeps `'35'` from reading as a scale answer.
_SCALE = "({a} GLOB '[1-5]' OR {a} GLOB '[1-5][^0-9]*')"
_IS_THREE = "({a} GLOB '3' OR {a} GLOB '3[^0-9]*')"

# Evidence from EITHER parse counts. Ours missing while theirs is present means
# our regex missed the line, not that the search found nothing.
_HAS_EVIDENCE = "(evidence_shape = 'present' OR ce_evidence_shape = 'present')"

# Whether ANY parse was in a position to see evidence for this answer.
#
# Measured on the real corpus 2026-08-04: `citation_evidence` covers exactly the
# runs whose prose parsed — 49,373 runs x 48 = 2,369,904 answers, to the unit —
# and is ABSENT for the 1,047 runs it does not. Those runs' 50,256 answers survive
# only through `answer_dict`, which carries no evidence at all.
#
# So for them "no evidence" is not an observation, it is our parse failing. Their
# prose exists; nothing here could read it. Counting a 3 among them as a
# default-3 would assert something unmeasurable — the exact failure invariant 5
# forbids — so they are excluded from the default-3 denominator and reported.
_EVIDENCE_OBSERVABLE = "(parsed_from = 'answers_text' OR ce_answer IS NOT NULL)"


@dataclass(frozen=True)
class QuestionRow:
    """One question's rates. Counts are stored; every rate is derived from them."""

    qnum: int
    n: int
    n_ev_seen: int
    n_scale: int
    n_text: int
    n_null: int
    n_default3: int
    n_noinfo: int
    n_cited: int
    n_dict_differ: int
    n_dict_comparable: int
    n_ce_differ: int
    n_ce_comparable: int
    n_runs_agree: int
    n_runs_multi: int

    @property
    def kind(self) -> str:
        """Scale, text or mixed — derived from the answers, never the question text.

        Question text varies per merchant (it carries their values inline) and
        carries PII, so classifying from it would be both unstable and unsafe.
        `mixed` is reported rather than resolved by a threshold: a question that
        answers on two regimes is itself a finding.
        """
        if self.n_scale and not self.n_text:
            return "scale"
        if self.n_text and not self.n_scale:
            return "text"
        return "mixed" if self.n_scale and self.n_text else "-"

    def _rate(self, num: int, den: int) -> float | None:
        return num / den if den else None

    @property
    def null_rate(self) -> float | None:
        return self._rate(self.n_null, self.n)

    @property
    def default3_rate(self) -> float | None:
        """Over answers where SOME parse could see evidence — see _EVIDENCE_OBSERVABLE."""
        return self._rate(self.n_default3, self.n_ev_seen)

    @property
    def noinfo_rate(self) -> float | None:
        return self._rate(self.n_noinfo, self.n)

    @property
    def citation_rate(self) -> float | None:
        return self._rate(self.n_cited, self.n)

    @property
    def dict_differ_rate(self) -> float | None:
        return self._rate(self.n_dict_differ, self.n_dict_comparable)

    @property
    def ce_differ_rate(self) -> float | None:
        return self._rate(self.n_ce_differ, self.n_ce_comparable)

    @property
    def agreement_rate(self) -> float | None:
        return self._rate(self.n_runs_agree, self.n_runs_multi)


@dataclass(frozen=True)
class Scorecard:
    """The whole per-question picture, plus what it had to leave out."""

    source: str
    rows: list[QuestionRow]
    by_source_null: dict[str, tuple[int, int]]  # source -> (n_null, n)
    n_answers: int
    parsed_from: list[tuple[str, int]]
    subqueries: SubqueryPicture

    @property
    def drop_candidates(self) -> list[QuestionRow]:
        """Questions ranked by how often their answer carried nothing."""
        return sorted(self.rows, key=lambda r: (-(r.noinfo_rate or 0.0), r.qnum))


@dataclass(frozen=True)
class SubqueryPicture:
    """Sub-queries per web-search run, against the 48 questions asked of it.

    Tests a hypothesis that would strengthen the deletion argument considerably:
    if each question provokes about one sub-query, then dropping a question drops
    a measurable slice of search volume rather than an unknown one.

    Deliberately reports the log-run and output-run counts side by side. They are
    different populations — 19,269 merchants have logs, 19,349 have outputs — and
    dividing a query total by the wrong one is how a coincidence becomes a
    finding.
    """

    n_log_runs: int
    n_output_runs: int
    n_queries: int
    n_at_48: int
    n_within_2: int

    @property
    def per_run(self) -> float | None:
        return self.n_queries / self.n_log_runs if self.n_log_runs else None


def question_scorecard(conn: sqlite3.Connection, source: str = "prose") -> Scorecard:
    """Per-question rates over `answers` and `citations`, as pure SQL.

    Two stdlib helpers are registered as SQL functions rather than reimplemented
    as SQL expressions. `is_null_answer` and `_norm_text` already define what this
    project means by "a NULL answer" and "the same answer", they are tested, and a
    second definition in SQL is exactly how the four-way evidence classification
    went wrong before. The cost is a Python call per row on a scan that is a scan
    either way.
    """
    if source not in ANSWER_SOURCES:
        raise ValueError(
            f"unknown answer source {source!r}; expected one of {sorted(ANSWER_SOURCES)}"
        )
    conn.create_function("coa_is_null", 1, lambda v: int(is_null_answer(v or "")))
    conn.create_function("coa_norm", 1, lambda v: _norm_text(v or ""))

    ans = f"TRIM({ANSWER_SOURCES[source]})"
    scale, is_three = _SCALE.format(a="ans"), _IS_THREE.format(a="ans")
    # `ev_seen` gates the default-3 half only. A NULL answer is a NULL answer
    # whichever parse produced it, so the NULL rate keeps the full denominator;
    # only the evidence-dependent half narrows. That makes `noinfo` UNDER-state
    # rather than over-state, which is the right direction to err in a document
    # arguing another team should spend less.
    default3 = f"({is_three} AND NOT has_ev AND ev_seen)"
    noinfo = f"(coa_is_null(ans) OR {default3})"

    # Citations are pre-aggregated to one row per (record, run, qnum) BEFORE the
    # join, which is load-bearing twice over. `citations` holds both sources for
    # the same fact — markdown_prose and citation_evidence — so counting rows
    # double-counts; and citation_evidence carries one entry per answer with a
    # NULL url most of the time, so counting entries rather than URLs would score
    # every question at 100%.
    rows = conn.execute(
        f"""
        WITH cited AS (
            SELECT output_id, run_id, qnum FROM citations
            WHERE url IS NOT NULL AND url != '' AND qnum IS NOT NULL
            GROUP BY output_id, run_id, qnum
        ), a AS (
            SELECT
                f.qnum                                        AS qnum,
                {ans}                                         AS ans,
                {_HAS_EVIDENCE}                               AS has_ev,
                {_EVIDENCE_OBSERVABLE}                        AS ev_seen,
                f.agree_with_dict                             AS ad,
                f.agree_with_ce                               AS ac,
                (c.qnum IS NOT NULL)                          AS has_cite
            FROM answer_facts f
            LEFT JOIN cited c
                   ON c.output_id = f.output_id
                  AND c.run_id IS f.run_id
                  AND c.qnum = f.qnum
            WHERE f.qnum IS NOT NULL
        )
        SELECT
            qnum,
            COUNT(*)                                              AS n,
            SUM({scale})                                          AS n_scale,
            SUM(NOT coa_is_null(ans) AND NOT {scale})             AS n_text,
            SUM(coa_is_null(ans))                                 AS n_null,
            SUM(ev_seen)                                          AS n_ev_seen,
            SUM({default3})                                       AS n_default3,
            SUM({noinfo})                                         AS n_noinfo,
            SUM(has_cite)                                         AS n_cited,
            SUM(ad = 0)                                           AS n_dict_differ,
            SUM(ad IS NOT NULL)                                   AS n_dict_cmp,
            SUM(ac = 0)                                           AS n_ce_differ,
            SUM(ac IS NOT NULL)                                   AS n_ce_cmp
        FROM a GROUP BY qnum ORDER BY qnum
        """
    ).fetchall()

    agreement = _inter_run_agreement(conn, source)
    return Scorecard(
        source=source,
        rows=[
            QuestionRow(
                qnum=r["qnum"],
                n=r["n"],
                n_ev_seen=r["n_ev_seen"] or 0,
                n_scale=r["n_scale"] or 0,
                n_text=r["n_text"] or 0,
                n_null=r["n_null"] or 0,
                n_default3=r["n_default3"] or 0,
                n_noinfo=r["n_noinfo"] or 0,
                n_cited=r["n_cited"] or 0,
                n_dict_differ=r["n_dict_differ"] or 0,
                n_dict_comparable=r["n_dict_cmp"] or 0,
                n_ce_differ=r["n_ce_differ"] or 0,
                n_ce_comparable=r["n_ce_cmp"] or 0,
                n_runs_agree=agreement.get(r["qnum"], (0, 0))[0],
                n_runs_multi=agreement.get(r["qnum"], (0, 0))[1],
            )
            for r in rows
        ],
        by_source_null=_null_rate_by_source(conn),
        n_answers=sum(r["n"] for r in rows),
        parsed_from=[
            (r[0] or "<unset>", r[1])
            for r in conn.execute(
                "SELECT parsed_from, COUNT(*) FROM answers GROUP BY 1 ORDER BY 2 DESC"
            )
        ],
        subqueries=_subquery_picture(conn),
    )


def _inter_run_agreement(conn: sqlite3.Connection, source: str) -> dict[int, tuple[int, int]]:
    """Per qnum, `(runs-agree, comparable)` across a merchant's repeated runs.

    A merchant is comparable only with 2+ runs, and agrees when every run gives
    the same normalized answer. This is the closest thing to a reliability signal
    available without ground truth: a question whose repeated runs disagree is one
    whose answer the pipeline is not actually determining.

    Grouped by `output_id` rather than `se10` because a duplicated se10 is stored
    as two records on purpose (DUP_OUTPUT_SE10) and merging them here would invent
    disagreement between two separate answer sets.
    """
    return {
        r["qnum"]: (r["n_agree"] or 0, r["n_groups"] or 0)
        for r in conn.execute(
            f"""
            SELECT qnum, SUM(n_distinct = 1) AS n_agree, COUNT(*) AS n_groups
            FROM (
                    SELECT qnum, output_id,
                       COUNT(DISTINCT coa_norm({ANSWER_SOURCES[source]})) AS n_distinct
                FROM answers
                WHERE qnum IS NOT NULL AND run_id IS NOT NULL
                GROUP BY qnum, output_id
                HAVING COUNT(DISTINCT run_id) >= 2
            )
            GROUP BY qnum
            """
        )
    }


def _null_rate_by_source(conn: sqlite3.Connection) -> dict[str, tuple[int, int]]:
    """The headline NULL rate as each parse sees it.

    50.5% of answers reading NULL is the largest number in this analysis, and it
    is computed from whichever parse is primary. Printing it once, unattributed,
    would hide the fact that it moves with that choice — so all sources report,
    over the rows where each actually has a value.
    """
    out: dict[str, tuple[int, int]] = {}
    for name, col in (("prose", "answer_text"), ("citation_evidence", "ce_answer")):
        row = conn.execute(
            f"SELECT SUM(coa_is_null({col})) AS n_null, COUNT({col}) AS n "
            f"FROM answers WHERE {col} IS NOT NULL"
        ).fetchone()
        out[name] = (row["n_null"] or 0, row["n"] or 0)
    return out


def _subquery_picture(conn: sqlite3.Connection) -> SubqueryPicture:
    """Sub-queries per web-search run, for the ~1:1-to-questions hypothesis."""
    row = conn.execute(
        """
        WITH per_run AS (
            SELECT r.id, COUNT(q.id) AS n_q
            FROM runs r
            LEFT JOIN search_calls c   ON c.run_pk = r.id
            LEFT JOIN query_instances q ON q.search_call_id = c.id
            GROUP BY r.id
        )
        SELECT COUNT(*) AS n_runs, COALESCE(SUM(n_q), 0) AS n_q,
               SUM(n_q = 48) AS at_48, SUM(ABS(n_q - 48) <= 2) AS within_2
        FROM per_run
        """
    ).fetchone()
    n_output_runs = conn.execute(
        "SELECT COUNT(*) FROM (SELECT 1 FROM answers WHERE run_id IS NOT NULL "
        "GROUP BY output_id, run_id)"
    ).fetchone()[0]
    return SubqueryPicture(
        n_log_runs=row["n_runs"] or 0,
        n_output_runs=n_output_runs or 0,
        n_queries=row["n_q"] or 0,
        n_at_48=row["at_48"] or 0,
        n_within_2=row["within_2"] or 0,
    )


def _pct(value: float | None) -> str:
    return "    -" if value is None else f"{value * 100:5.1f}"


def _evidence_observable_line(sc: Scorecard) -> str:
    """Name the answers `d3` had to exclude, and why — never silently narrow it.

    These are runs where no parse could read the prose, so "no evidence" would be
    our failure rather than a measurement. `noinfo` therefore under-states for
    them, which is the safe direction; saying nothing would leave a reader
    assuming the full corpus was scored.
    """
    seen = sum(r.n_ev_seen for r in sc.rows)
    blind = sc.n_answers - seen
    if not blind:
        return "  d3 denominator     all answers (every one had a parse that could see evidence)"
    return (
        f"  d3 denominator     {seen:,} of {sc.n_answers:,} — excludes {blind:,} answers whose\n"
        f"                     run no parse could read, so evidence was never observable"
    )


def render_scorecard(sc: Scorecard, top: int = 10) -> str:
    """The scorecard as one paste-ready block. No question text — see module docstring."""
    if not sc.rows:
        return "QUESTION SCORECARD\n  (no answers ingested)"

    out = [
        "QUESTION SCORECARD",
        f"  answer source      {sc.source}  ({ANSWER_SOURCES[sc.source]})",
        f"  answers            {sc.n_answers:,} over {len(sc.rows)} questions",
        _evidence_observable_line(sc),
        "  all columns are % of that question's n, except n itself and d3",
        "",
        "     Q        n  kind    null     d3  noinfo   cite   dict≠    ce≠  agree",
    ]
    for r in sc.rows:
        out.append(
            f"  {r.qnum:>4} {r.n:>8,}  {r.kind:<6}{_pct(r.null_rate)} "
            f"{_pct(r.default3_rate)}  {_pct(r.noinfo_rate)}  {_pct(r.citation_rate)}  "
            f"{_pct(r.dict_differ_rate)}  {_pct(r.ce_differ_rate)}  {_pct(r.agreement_rate)}"
        )

    out += ["", "  DROP CANDIDATES (highest `noinfo` — the answer carried nothing)"]
    ranked = sc.drop_candidates
    for r in ranked[:top]:
        # Components as COUNTS, not rates. `noinfo` is over n while `d3` is over
        # the observable subset, so printing both as percentages here would read
        # as a decomposition that does not add up.
        out.append(
            f"  {r.qnum:>4}  noinfo {_pct(r.noinfo_rate)}%  "
            f"(NULL {r.n_null:,} + default-3 {r.n_default3:,} of {r.n:,})  "
            f"cited {_pct(r.citation_rate)}%  {r.kind}"
        )
    if len(ranked) > top:
        out.append(f"  ... {len(ranked) - top} more questions, all listed in the table above")

    out += ["", "  NULL RATE BY SOURCE (the headline moves with whose parse is primary)"]
    for name, (n_null, n) in sc.by_source_null.items():
        rate = f"{n_null / n:.1%}" if n else "n/a"
        out.append(f"    {name:<18} {rate:>7}  of {n:,} answers it parsed")
    out.append("    " + ", ".join(f"{src} {n:,}" for src, n in sc.parsed_from) + "  (parsed_from)")

    out += ["", _render_subqueries(sc.subqueries)]
    out += [
        "",
        "  Reading this:",
        "    * high `noinfo` + low `cite`  -> the question is buying search calls and",
        "      returning a constant. The strongest deletion case available without labels.",
        "    * high `noinfo` + high `cite` -> searches ARE finding pages; the question or",
        "      its threshold is discarding what they found. Rewrite before deleting.",
        "    * low `agree`                 -> repeated runs disagree, so the pipeline is not",
        "      determining this answer. Unreliable, but not therefore droppable.",
        "    * `dict≠` / `ce≠` are OUR parse vs THEIRS, never a fact about the merchant.",
        "      A question high on either is one where the answer format differs, and its",
        "      other columns should be re-read under --answer-source ce before being used.",
    ]
    return "\n".join(out)


def _render_subqueries(s: SubqueryPicture) -> str:
    """The ~1:1 question-to-sub-query hypothesis, with its denominators visible."""
    if not s.n_log_runs:
        return "  SUB-QUERIES PER RUN\n    (no web-search runs ingested)"
    out = [
        "  SUB-QUERIES PER RUN  (vs 48 questions asked of each)",
        f"    log runs         {s.n_log_runs:,}   (output runs {s.n_output_runs:,} — "
        f"{'same population' if s.n_log_runs == s.n_output_runs else 'DIFFERENT populations'})",
        f"    query entries    {s.n_queries:,}",
        f"    per run          {s.per_run:.2f}" if s.per_run else "    per run          n/a",
        f"    exactly 48       {s.n_at_48:,} runs ({s.n_at_48 / s.n_log_runs:.1%})",
        f"    within +/-2      {s.n_within_2:,} runs ({s.n_within_2 / s.n_log_runs:.1%})",
    ]
    if s.n_log_runs != s.n_output_runs:
        out.append("    The two run counts differ, so `per run` divides queries by a population")
        out.append(
            "    that is not the one answering 48 questions. A mean near 48 is a coincidence"
        )
        out.append("    until they reconcile — read `exactly 48`, not the mean.")
    return "\n".join(out)
